export enum EmailType {
  // SendGrid dynamic template (pass template_id directly)
  SENDGRID_TEMPLATE = 'SENDGRID_TEMPLATE',

  // Broadcast / event emails
  BROADCAST_EVENT_ANNOUNCEMENT = 'BROADCAST_EVENT_ANNOUNCEMENT',
  BROADCAST_PRE_EVENT_REMINDER = 'BROADCAST_PRE_EVENT_REMINDER',
  BROADCAST_POST_EVENT_FOLLOWUP = 'BROADCAST_POST_EVENT_FOLLOWUP',

  // Order-related
  BUYER_ORDER_CONFIRMATION = 'BUYER_ORDER_CONFIRMATION',
  ORG_NEW_ORDER_NOTIFICATION = 'ORG_NEW_ORDER_NOTIFICATION',

  // Ticket-related
  BUYER_EVENT_CONFIRMATION_TICKETS = 'BUYER_EVENT_CONFIRMATION_TICKETS',

  // Waitlist (future)
  BROADCAST_WAITLIST_NOTIFY = 'BROADCAST_WAITLIST_NOTIFY',
}

export enum EmailStatus {
  PENDING = 'PENDING',
  QUEUED = 'QUEUED',
  SENT = 'SENT',
  FAILED = 'FAILED',
  BOUNCED = 'BOUNCED',
  DELIVERED = 'DELIVERED',
}

export enum BroadcastStatus {
  DRAFT = 'DRAFT',
  SCHEDULED = 'SCHEDULED',
  QUEUED = 'QUEUED',
  SENT = 'SENT',
  FAILED = 'FAILED',
}
