export enum EmailType {
  // SendGrid dynamic template (pass template_id directly)
  SENDGRID_TEMPLATE = 'SENDGRID_TEMPLATE',

  // Broadcast / event emails
  BROADCAST_EVENT_ANNOUNCEMENT = 'BROADCAST_EVENT_ANNOUNCEMENT',
  BROADCAST_PRE_EVENT_REMINDER = 'BROADCAST_PRE_EVENT_REMINDER',
  BROADCAST_POST_EVENT_FOLLOWUP = 'BROADCAST_POST_EVENT_FOLLOWUP',

  // Order-related
  BUYER_ORDER_CONFIRMATION = 'BUYER_ORDER_CONFIRMATION',
  ORG_NEW_ORDER_NOTIFICATION = 'ORG_NEW_ORDER_NOTIFICATION',

  // Ticket-related
  BUYER_EVENT_CONFIRMATION_TICKETS = 'BUYER_EVENT_CONFIRMATION_TICKETS',

  // Waitlist (future)
  BROADCAST_WAITLIST_NOTIFY = 'BROADCAST_WAITLIST_NOTIFY',

  // ── HearMEE — Session submission & approval ─────────────────────────────────
  // Speaker notifications
  HEARMEE_SPEAKER_SESSION_SUBMITTED   = 'HEARMEE_SPEAKER_SESSION_SUBMITTED',
  HEARMEE_SPEAKER_SESSION_APPROVED    = 'HEARMEE_SPEAKER_SESSION_APPROVED',
  HEARMEE_SPEAKER_SESSION_DECLINED    = 'HEARMEE_SPEAKER_SESSION_DECLINED',
  HEARMEE_SPEAKER_SESSION_SCHEDULED   = 'HEARMEE_SPEAKER_SESSION_SCHEDULED',
  HEARMEE_SPEAKER_SESSION_RESCHEDULED = 'HEARMEE_SPEAKER_SESSION_RESCHEDULED',
  HEARMEE_SPEAKER_SESSION_UNSCHEDULED = 'HEARMEE_SPEAKER_SESSION_UNSCHEDULED',
  // Organizer notifications
  HEARMEE_ORGANIZER_NEW_SUBMISSION    = 'HEARMEE_ORGANIZER_NEW_SUBMISSION',
  HEARMEE_ORGANIZER_EVENT_PUBLISHED   = 'HEARMEE_ORGANIZER_EVENT_PUBLISHED',
  HEARMEE_ORGANIZER_SPEAKER_ACCEPTED  = 'HEARMEE_ORGANIZER_SPEAKER_ACCEPTED',
  HEARMEE_ORGANIZER_SPEAKER_DECLINED  = 'HEARMEE_ORGANIZER_SPEAKER_DECLINED',
  // Approver / reviewer notifications
  HEARMEE_APPROVER_REVIEW_REQUEST     = 'HEARMEE_APPROVER_REVIEW_REQUEST',
  HEARMEE_APPROVER_REVIEWER_INVITE    = 'HEARMEE_APPROVER_REVIEWER_INVITE',
  // Track Chair notifications
  HEARMEE_TRACKCHAIR_NEW_SUBMISSION   = 'HEARMEE_TRACKCHAIR_NEW_SUBMISSION',
  // Schedule notifications
  HEARMEE_SCHEDULE_SESSION_SCHEDULED  = 'HEARMEE_SCHEDULE_SESSION_SCHEDULED',
  HEARMEE_SCHEDULE_PUBLISHED          = 'HEARMEE_SCHEDULE_PUBLISHED',
}

export enum EmailStatus {
  PENDING = 'PENDING',
  QUEUED = 'QUEUED',
  SENT = 'SENT',
  FAILED = 'FAILED',
  BOUNCED = 'BOUNCED',
  DELIVERED = 'DELIVERED',
}

export enum BroadcastStatus {
  DRAFT = 'DRAFT',
  SCHEDULED = 'SCHEDULED',
  QUEUED = 'QUEUED',
  SENT = 'SENT',
  FAILED = 'FAILED',
}
